// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QuizspbCreateQuizRequest quizspb create quiz request
//
// swagger:model quizspbCreateQuizRequest
type QuizspbCreateQuizRequest struct {

	// name
	Name string `json:"name,omitempty"`

	// quiz type
	QuizType string `json:"quizType,omitempty"`
}

// Validate validates this quizspb create quiz request
func (m *QuizspbCreateQuizRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this quizspb create quiz request based on context it is used
func (m *QuizspbCreateQuizRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QuizspbCreateQuizRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuizspbCreateQuizRequest) UnmarshalBinary(b []byte) error {
	var res QuizspbCreateQuizRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
