// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QuizspbQuiz quizspb quiz
//
// swagger:model quizspbQuiz
type QuizspbQuiz struct {

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// quiz type
	QuizType string `json:"quizType,omitempty"`
}

// Validate validates this quizspb quiz
func (m *QuizspbQuiz) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this quizspb quiz based on context it is used
func (m *QuizspbQuiz) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QuizspbQuiz) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuizspbQuiz) UnmarshalBinary(b []byte) error {
	var res QuizspbQuiz
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
