// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QuizsServiceChangeEmailBody quizs service change email body
//
// swagger:model QuizsServiceChangeEmailBody
type QuizsServiceChangeEmailBody struct {

	// quiz type
	QuizType string `json:"quizType,omitempty"`
}

// Validate validates this quizs service change email body
func (m *QuizsServiceChangeEmailBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this quizs service change email body based on context it is used
func (m *QuizsServiceChangeEmailBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QuizsServiceChangeEmailBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuizsServiceChangeEmailBody) UnmarshalBinary(b []byte) error {
	var res QuizsServiceChangeEmailBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
