// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QuizspbGetQuizResponse quizspb get quiz response
//
// swagger:model quizspbGetQuizResponse
type QuizspbGetQuizResponse struct {

	// quiz
	Quiz *QuizspbQuiz `json:"quiz,omitempty"`
}

// Validate validates this quizspb get quiz response
func (m *QuizspbGetQuizResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQuiz(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QuizspbGetQuizResponse) validateQuiz(formats strfmt.Registry) error {
	if swag.IsZero(m.Quiz) { // not required
		return nil
	}

	if m.Quiz != nil {
		if err := m.Quiz.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("quiz")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("quiz")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this quizspb get quiz response based on the context it is used
func (m *QuizspbGetQuizResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateQuiz(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QuizspbGetQuizResponse) contextValidateQuiz(ctx context.Context, formats strfmt.Registry) error {

	if m.Quiz != nil {

		if swag.IsZero(m.Quiz) { // not required
			return nil
		}

		if err := m.Quiz.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("quiz")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("quiz")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *QuizspbGetQuizResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuizspbGetQuizResponse) UnmarshalBinary(b []byte) error {
	var res QuizspbGetQuizResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
