// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"quizazz/user-service/usersclient/models"
)

// NewChangeEmailParams creates a new ChangeEmailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChangeEmailParams() *ChangeEmailParams {
	return &ChangeEmailParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChangeEmailParamsWithTimeout creates a new ChangeEmailParams object
// with the ability to set a timeout on a request.
func NewChangeEmailParamsWithTimeout(timeout time.Duration) *ChangeEmailParams {
	return &ChangeEmailParams{
		timeout: timeout,
	}
}

// NewChangeEmailParamsWithContext creates a new ChangeEmailParams object
// with the ability to set a context for a request.
func NewChangeEmailParamsWithContext(ctx context.Context) *ChangeEmailParams {
	return &ChangeEmailParams{
		Context: ctx,
	}
}

// NewChangeEmailParamsWithHTTPClient creates a new ChangeEmailParams object
// with the ability to set a custom HTTPClient for a request.
func NewChangeEmailParamsWithHTTPClient(client *http.Client) *ChangeEmailParams {
	return &ChangeEmailParams{
		HTTPClient: client,
	}
}

/*
ChangeEmailParams contains all the parameters to send to the API endpoint

	for the change email operation.

	Typically these are written to a http.Request.
*/
type ChangeEmailParams struct {

	// Body.
	Body *models.UsersServiceChangeEmailBody

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the change email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChangeEmailParams) WithDefaults() *ChangeEmailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the change email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChangeEmailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the change email params
func (o *ChangeEmailParams) WithTimeout(timeout time.Duration) *ChangeEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change email params
func (o *ChangeEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change email params
func (o *ChangeEmailParams) WithContext(ctx context.Context) *ChangeEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change email params
func (o *ChangeEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change email params
func (o *ChangeEmailParams) WithHTTPClient(client *http.Client) *ChangeEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change email params
func (o *ChangeEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change email params
func (o *ChangeEmailParams) WithBody(body *models.UsersServiceChangeEmailBody) *ChangeEmailParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change email params
func (o *ChangeEmailParams) SetBody(body *models.UsersServiceChangeEmailBody) {
	o.Body = body
}

// WithID adds the id to the change email params
func (o *ChangeEmailParams) WithID(id string) *ChangeEmailParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the change email params
func (o *ChangeEmailParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
