// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UsersServiceChangeEmailBody users service change email body
//
// swagger:model UsersServiceChangeEmailBody
type UsersServiceChangeEmailBody struct {

	// email
	Email string `json:"email,omitempty"`
}

// Validate validates this users service change email body
func (m *UsersServiceChangeEmailBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this users service change email body based on context it is used
func (m *UsersServiceChangeEmailBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UsersServiceChangeEmailBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UsersServiceChangeEmailBody) UnmarshalBinary(b []byte) error {
	var res UsersServiceChangeEmailBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
