// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: quizspb/messages.proto

package quizspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuizCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	QuizType string `protobuf:"bytes,3,opt,name=quizType,proto3" json:"quizType,omitempty"`
}

func (x *QuizCreated) Reset() {
	*x = QuizCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizspb_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizCreated) ProtoMessage() {}

func (x *QuizCreated) ProtoReflect() protoreflect.Message {
	mi := &file_quizspb_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizCreated.ProtoReflect.Descriptor instead.
func (*QuizCreated) Descriptor() ([]byte, []int) {
	return file_quizspb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *QuizCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuizCreated) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

type QuizEmailChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizType string `protobuf:"bytes,2,opt,name=quizType,proto3" json:"quizType,omitempty"`
}

func (x *QuizEmailChanged) Reset() {
	*x = QuizEmailChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizspb_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizEmailChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizEmailChanged) ProtoMessage() {}

func (x *QuizEmailChanged) ProtoReflect() protoreflect.Message {
	mi := &file_quizspb_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizEmailChanged.ProtoReflect.Descriptor instead.
func (*QuizEmailChanged) Descriptor() ([]byte, []int) {
	return file_quizspb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *QuizEmailChanged) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizEmailChanged) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

type QuizEnabled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *QuizEnabled) Reset() {
	*x = QuizEnabled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizspb_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizEnabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizEnabled) ProtoMessage() {}

func (x *QuizEnabled) ProtoReflect() protoreflect.Message {
	mi := &file_quizspb_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizEnabled.ProtoReflect.Descriptor instead.
func (*QuizEnabled) Descriptor() ([]byte, []int) {
	return file_quizspb_messages_proto_rawDescGZIP(), []int{2}
}

func (x *QuizEnabled) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QuizDisabled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *QuizDisabled) Reset() {
	*x = QuizDisabled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizspb_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizDisabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizDisabled) ProtoMessage() {}

func (x *QuizDisabled) ProtoReflect() protoreflect.Message {
	mi := &file_quizspb_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizDisabled.ProtoReflect.Descriptor instead.
func (*QuizDisabled) Descriptor() ([]byte, []int) {
	return file_quizspb_messages_proto_rawDescGZIP(), []int{3}
}

func (x *QuizDisabled) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuthorizeQuiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AuthorizeQuiz) Reset() {
	*x = AuthorizeQuiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizspb_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeQuiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeQuiz) ProtoMessage() {}

func (x *AuthorizeQuiz) ProtoReflect() protoreflect.Message {
	mi := &file_quizspb_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeQuiz.ProtoReflect.Descriptor instead.
func (*AuthorizeQuiz) Descriptor() ([]byte, []int) {
	return file_quizspb_messages_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizeQuiz) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_quizspb_messages_proto protoreflect.FileDescriptor

var file_quizspb_messages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x71, 0x75, 0x69, 0x7a, 0x73, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x71, 0x75, 0x69, 0x7a, 0x73, 0x70,
	0x62, 0x22, 0x4d, 0x0a, 0x0b, 0x51, 0x75, 0x69, 0x7a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x3e, 0x0a, 0x10, 0x51, 0x75, 0x69, 0x7a, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x1d, 0x0a, 0x0b, 0x51, 0x75, 0x69, 0x7a, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x1e, 0x0a, 0x0c, 0x51, 0x75, 0x69, 0x7a, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x1f, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x51, 0x75, 0x69, 0x7a,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x42, 0x85, 0x01, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x73, 0x70, 0x62,
	0x42, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x2b, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x61, 0x7a, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x70, 0x62, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x73, 0x70, 0x62, 0xa2, 0x02,
	0x03, 0x51, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x51, 0x75, 0x69, 0x7a, 0x73, 0x70, 0x62, 0xca, 0x02,
	0x07, 0x51, 0x75, 0x69, 0x7a, 0x73, 0x70, 0x62, 0xe2, 0x02, 0x13, 0x51, 0x75, 0x69, 0x7a, 0x73,
	0x70, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x07, 0x51, 0x75, 0x69, 0x7a, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quizspb_messages_proto_rawDescOnce sync.Once
	file_quizspb_messages_proto_rawDescData = file_quizspb_messages_proto_rawDesc
)

func file_quizspb_messages_proto_rawDescGZIP() []byte {
	file_quizspb_messages_proto_rawDescOnce.Do(func() {
		file_quizspb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_quizspb_messages_proto_rawDescData)
	})
	return file_quizspb_messages_proto_rawDescData
}

var file_quizspb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_quizspb_messages_proto_goTypes = []interface{}{
	(*QuizCreated)(nil),      // 0: quizspb.QuizCreated
	(*QuizEmailChanged)(nil), // 1: quizspb.QuizEmailChanged
	(*QuizEnabled)(nil),      // 2: quizspb.QuizEnabled
	(*QuizDisabled)(nil),     // 3: quizspb.QuizDisabled
	(*AuthorizeQuiz)(nil),    // 4: quizspb.AuthorizeQuiz
}
var file_quizspb_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quizspb_messages_proto_init() }
func file_quizspb_messages_proto_init() {
	if File_quizspb_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quizspb_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuizCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quizspb_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuizEmailChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quizspb_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuizEnabled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quizspb_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuizDisabled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quizspb_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeQuiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quizspb_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quizspb_messages_proto_goTypes,
		DependencyIndexes: file_quizspb_messages_proto_depIdxs,
		MessageInfos:      file_quizspb_messages_proto_msgTypes,
	}.Build()
	File_quizspb_messages_proto = out.File
	file_quizspb_messages_proto_rawDesc = nil
	file_quizspb_messages_proto_goTypes = nil
	file_quizspb_messages_proto_depIdxs = nil
}
