// Code generated by go-swagger; DO NOT EDIT.

package quiz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quizazz/quiz-service/quizsclient/models"
)

// ChangeEmailReader is a Reader for the ChangeEmail structure.
type ChangeEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewChangeEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewChangeEmailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewChangeEmailOK creates a ChangeEmailOK with default headers values
func NewChangeEmailOK() *ChangeEmailOK {
	return &ChangeEmailOK{}
}

/*
ChangeEmailOK describes a response with status code 200, with default header values.

A successful response.
*/
type ChangeEmailOK struct {
	Payload models.QuizspbChangeEmailResponse
}

// IsSuccess returns true when this change email o k response has a 2xx status code
func (o *ChangeEmailOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this change email o k response has a 3xx status code
func (o *ChangeEmailOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this change email o k response has a 4xx status code
func (o *ChangeEmailOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this change email o k response has a 5xx status code
func (o *ChangeEmailOK) IsServerError() bool {
	return false
}

// IsCode returns true when this change email o k response a status code equal to that given
func (o *ChangeEmailOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the change email o k response
func (o *ChangeEmailOK) Code() int {
	return 200
}

func (o *ChangeEmailOK) Error() string {
	return fmt.Sprintf("[PUT /api/quizs/{id}/change-email][%d] changeEmailOK  %+v", 200, o.Payload)
}

func (o *ChangeEmailOK) String() string {
	return fmt.Sprintf("[PUT /api/quizs/{id}/change-email][%d] changeEmailOK  %+v", 200, o.Payload)
}

func (o *ChangeEmailOK) GetPayload() models.QuizspbChangeEmailResponse {
	return o.Payload
}

func (o *ChangeEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChangeEmailDefault creates a ChangeEmailDefault with default headers values
func NewChangeEmailDefault(code int) *ChangeEmailDefault {
	return &ChangeEmailDefault{
		_statusCode: code,
	}
}

/*
ChangeEmailDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ChangeEmailDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this change email default response has a 2xx status code
func (o *ChangeEmailDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this change email default response has a 3xx status code
func (o *ChangeEmailDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this change email default response has a 4xx status code
func (o *ChangeEmailDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this change email default response has a 5xx status code
func (o *ChangeEmailDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this change email default response a status code equal to that given
func (o *ChangeEmailDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the change email default response
func (o *ChangeEmailDefault) Code() int {
	return o._statusCode
}

func (o *ChangeEmailDefault) Error() string {
	return fmt.Sprintf("[PUT /api/quizs/{id}/change-email][%d] changeEmail default  %+v", o._statusCode, o.Payload)
}

func (o *ChangeEmailDefault) String() string {
	return fmt.Sprintf("[PUT /api/quizs/{id}/change-email][%d] changeEmail default  %+v", o._statusCode, o.Payload)
}

func (o *ChangeEmailDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ChangeEmailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
