// Code generated by go-swagger; DO NOT EDIT.

package quiz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"quizazz/quiz-service/quizsclient/models"
)

// NewEnableQuizParams creates a new EnableQuizParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEnableQuizParams() *EnableQuizParams {
	return &EnableQuizParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEnableQuizParamsWithTimeout creates a new EnableQuizParams object
// with the ability to set a timeout on a request.
func NewEnableQuizParamsWithTimeout(timeout time.Duration) *EnableQuizParams {
	return &EnableQuizParams{
		timeout: timeout,
	}
}

// NewEnableQuizParamsWithContext creates a new EnableQuizParams object
// with the ability to set a context for a request.
func NewEnableQuizParamsWithContext(ctx context.Context) *EnableQuizParams {
	return &EnableQuizParams{
		Context: ctx,
	}
}

// NewEnableQuizParamsWithHTTPClient creates a new EnableQuizParams object
// with the ability to set a custom HTTPClient for a request.
func NewEnableQuizParamsWithHTTPClient(client *http.Client) *EnableQuizParams {
	return &EnableQuizParams{
		HTTPClient: client,
	}
}

/*
EnableQuizParams contains all the parameters to send to the API endpoint

	for the enable quiz operation.

	Typically these are written to a http.Request.
*/
type EnableQuizParams struct {

	// Body.
	Body models.QuizsServiceEnableQuizBody

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the enable quiz params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnableQuizParams) WithDefaults() *EnableQuizParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the enable quiz params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnableQuizParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the enable quiz params
func (o *EnableQuizParams) WithTimeout(timeout time.Duration) *EnableQuizParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the enable quiz params
func (o *EnableQuizParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the enable quiz params
func (o *EnableQuizParams) WithContext(ctx context.Context) *EnableQuizParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the enable quiz params
func (o *EnableQuizParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the enable quiz params
func (o *EnableQuizParams) WithHTTPClient(client *http.Client) *EnableQuizParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the enable quiz params
func (o *EnableQuizParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the enable quiz params
func (o *EnableQuizParams) WithBody(body models.QuizsServiceEnableQuizBody) *EnableQuizParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the enable quiz params
func (o *EnableQuizParams) SetBody(body models.QuizsServiceEnableQuizBody) {
	o.Body = body
}

// WithID adds the id to the enable quiz params
func (o *EnableQuizParams) WithID(id string) *EnableQuizParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the enable quiz params
func (o *EnableQuizParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EnableQuizParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
