// Code generated by go-swagger; DO NOT EDIT.

package quiz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quizazz/quiz-service/quizsclient/models"
)

// EnableQuizReader is a Reader for the EnableQuiz structure.
type EnableQuizReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnableQuizReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEnableQuizOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEnableQuizDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEnableQuizOK creates a EnableQuizOK with default headers values
func NewEnableQuizOK() *EnableQuizOK {
	return &EnableQuizOK{}
}

/*
EnableQuizOK describes a response with status code 200, with default header values.

A successful response.
*/
type EnableQuizOK struct {
	Payload models.QuizspbEnableQuizResponse
}

// IsSuccess returns true when this enable quiz o k response has a 2xx status code
func (o *EnableQuizOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this enable quiz o k response has a 3xx status code
func (o *EnableQuizOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this enable quiz o k response has a 4xx status code
func (o *EnableQuizOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this enable quiz o k response has a 5xx status code
func (o *EnableQuizOK) IsServerError() bool {
	return false
}

// IsCode returns true when this enable quiz o k response a status code equal to that given
func (o *EnableQuizOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the enable quiz o k response
func (o *EnableQuizOK) Code() int {
	return 200
}

func (o *EnableQuizOK) Error() string {
	return fmt.Sprintf("[PUT /api/quizs/{id}/enable][%d] enableQuizOK  %+v", 200, o.Payload)
}

func (o *EnableQuizOK) String() string {
	return fmt.Sprintf("[PUT /api/quizs/{id}/enable][%d] enableQuizOK  %+v", 200, o.Payload)
}

func (o *EnableQuizOK) GetPayload() models.QuizspbEnableQuizResponse {
	return o.Payload
}

func (o *EnableQuizOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableQuizDefault creates a EnableQuizDefault with default headers values
func NewEnableQuizDefault(code int) *EnableQuizDefault {
	return &EnableQuizDefault{
		_statusCode: code,
	}
}

/*
EnableQuizDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EnableQuizDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this enable quiz default response has a 2xx status code
func (o *EnableQuizDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this enable quiz default response has a 3xx status code
func (o *EnableQuizDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this enable quiz default response has a 4xx status code
func (o *EnableQuizDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this enable quiz default response has a 5xx status code
func (o *EnableQuizDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this enable quiz default response a status code equal to that given
func (o *EnableQuizDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the enable quiz default response
func (o *EnableQuizDefault) Code() int {
	return o._statusCode
}

func (o *EnableQuizDefault) Error() string {
	return fmt.Sprintf("[PUT /api/quizs/{id}/enable][%d] enableQuiz default  %+v", o._statusCode, o.Payload)
}

func (o *EnableQuizDefault) String() string {
	return fmt.Sprintf("[PUT /api/quizs/{id}/enable][%d] enableQuiz default  %+v", o._statusCode, o.Payload)
}

func (o *EnableQuizDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *EnableQuizDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
