// Code generated by go-swagger; DO NOT EDIT.

package quiz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetQuizParams creates a new GetQuizParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetQuizParams() *GetQuizParams {
	return &GetQuizParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetQuizParamsWithTimeout creates a new GetQuizParams object
// with the ability to set a timeout on a request.
func NewGetQuizParamsWithTimeout(timeout time.Duration) *GetQuizParams {
	return &GetQuizParams{
		timeout: timeout,
	}
}

// NewGetQuizParamsWithContext creates a new GetQuizParams object
// with the ability to set a context for a request.
func NewGetQuizParamsWithContext(ctx context.Context) *GetQuizParams {
	return &GetQuizParams{
		Context: ctx,
	}
}

// NewGetQuizParamsWithHTTPClient creates a new GetQuizParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetQuizParamsWithHTTPClient(client *http.Client) *GetQuizParams {
	return &GetQuizParams{
		HTTPClient: client,
	}
}

/*
GetQuizParams contains all the parameters to send to the API endpoint

	for the get quiz operation.

	Typically these are written to a http.Request.
*/
type GetQuizParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get quiz params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetQuizParams) WithDefaults() *GetQuizParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get quiz params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetQuizParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get quiz params
func (o *GetQuizParams) WithTimeout(timeout time.Duration) *GetQuizParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get quiz params
func (o *GetQuizParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get quiz params
func (o *GetQuizParams) WithContext(ctx context.Context) *GetQuizParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get quiz params
func (o *GetQuizParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get quiz params
func (o *GetQuizParams) WithHTTPClient(client *http.Client) *GetQuizParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get quiz params
func (o *GetQuizParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get quiz params
func (o *GetQuizParams) WithID(id string) *GetQuizParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get quiz params
func (o *GetQuizParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetQuizParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
