// Code generated by go-swagger; DO NOT EDIT.

package quiz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quizazz/quiz-service/quizsclient/models"
)

// GetQuizReader is a Reader for the GetQuiz structure.
type GetQuizReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQuizReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetQuizOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetQuizDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetQuizOK creates a GetQuizOK with default headers values
func NewGetQuizOK() *GetQuizOK {
	return &GetQuizOK{}
}

/*
GetQuizOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetQuizOK struct {
	Payload *models.QuizspbGetQuizResponse
}

// IsSuccess returns true when this get quiz o k response has a 2xx status code
func (o *GetQuizOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get quiz o k response has a 3xx status code
func (o *GetQuizOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get quiz o k response has a 4xx status code
func (o *GetQuizOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get quiz o k response has a 5xx status code
func (o *GetQuizOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get quiz o k response a status code equal to that given
func (o *GetQuizOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get quiz o k response
func (o *GetQuizOK) Code() int {
	return 200
}

func (o *GetQuizOK) Error() string {
	return fmt.Sprintf("[GET /api/quizs/{id}][%d] getQuizOK  %+v", 200, o.Payload)
}

func (o *GetQuizOK) String() string {
	return fmt.Sprintf("[GET /api/quizs/{id}][%d] getQuizOK  %+v", 200, o.Payload)
}

func (o *GetQuizOK) GetPayload() *models.QuizspbGetQuizResponse {
	return o.Payload
}

func (o *GetQuizOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.QuizspbGetQuizResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetQuizDefault creates a GetQuizDefault with default headers values
func NewGetQuizDefault(code int) *GetQuizDefault {
	return &GetQuizDefault{
		_statusCode: code,
	}
}

/*
GetQuizDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetQuizDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get quiz default response has a 2xx status code
func (o *GetQuizDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get quiz default response has a 3xx status code
func (o *GetQuizDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get quiz default response has a 4xx status code
func (o *GetQuizDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get quiz default response has a 5xx status code
func (o *GetQuizDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get quiz default response a status code equal to that given
func (o *GetQuizDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get quiz default response
func (o *GetQuizDefault) Code() int {
	return o._statusCode
}

func (o *GetQuizDefault) Error() string {
	return fmt.Sprintf("[GET /api/quizs/{id}][%d] getQuiz default  %+v", o._statusCode, o.Payload)
}

func (o *GetQuizDefault) String() string {
	return fmt.Sprintf("[GET /api/quizs/{id}][%d] getQuiz default  %+v", o._statusCode, o.Payload)
}

func (o *GetQuizDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetQuizDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
