// Code generated by go-swagger; DO NOT EDIT.

package quiz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"quizazz/quiz-service/quizsclient/models"
)

// NewRegisterQuizParams creates a new RegisterQuizParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegisterQuizParams() *RegisterQuizParams {
	return &RegisterQuizParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterQuizParamsWithTimeout creates a new RegisterQuizParams object
// with the ability to set a timeout on a request.
func NewRegisterQuizParamsWithTimeout(timeout time.Duration) *RegisterQuizParams {
	return &RegisterQuizParams{
		timeout: timeout,
	}
}

// NewRegisterQuizParamsWithContext creates a new RegisterQuizParams object
// with the ability to set a context for a request.
func NewRegisterQuizParamsWithContext(ctx context.Context) *RegisterQuizParams {
	return &RegisterQuizParams{
		Context: ctx,
	}
}

// NewRegisterQuizParamsWithHTTPClient creates a new RegisterQuizParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegisterQuizParamsWithHTTPClient(client *http.Client) *RegisterQuizParams {
	return &RegisterQuizParams{
		HTTPClient: client,
	}
}

/*
RegisterQuizParams contains all the parameters to send to the API endpoint

	for the register quiz operation.

	Typically these are written to a http.Request.
*/
type RegisterQuizParams struct {

	// Body.
	Body *models.QuizspbCreateQuizRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the register quiz params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterQuizParams) WithDefaults() *RegisterQuizParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the register quiz params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterQuizParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the register quiz params
func (o *RegisterQuizParams) WithTimeout(timeout time.Duration) *RegisterQuizParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register quiz params
func (o *RegisterQuizParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register quiz params
func (o *RegisterQuizParams) WithContext(ctx context.Context) *RegisterQuizParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register quiz params
func (o *RegisterQuizParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register quiz params
func (o *RegisterQuizParams) WithHTTPClient(client *http.Client) *RegisterQuizParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register quiz params
func (o *RegisterQuizParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the register quiz params
func (o *RegisterQuizParams) WithBody(body *models.QuizspbCreateQuizRequest) *RegisterQuizParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the register quiz params
func (o *RegisterQuizParams) SetBody(body *models.QuizspbCreateQuizRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterQuizParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
