// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: quizspb/messages.proto

package userspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRegistered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UserRegistered) Reset() {
	*x = UserRegistered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userspb_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistered) ProtoMessage() {}

func (x *UserRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistered.ProtoReflect.Descriptor instead.
func (*UserRegistered) Descriptor() ([]byte, []int) {
	return file_userspb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegistered) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserRegistered) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRegistered) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserEmailChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UserEmailChanged) Reset() {
	*x = UserEmailChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userspb_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEmailChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmailChanged) ProtoMessage() {}

func (x *UserEmailChanged) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmailChanged.ProtoReflect.Descriptor instead.
func (*UserEmailChanged) Descriptor() ([]byte, []int) {
	return file_userspb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UserEmailChanged) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserEmailChanged) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserEnabled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserEnabled) Reset() {
	*x = UserEnabled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userspb_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEnabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEnabled) ProtoMessage() {}

func (x *UserEnabled) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEnabled.ProtoReflect.Descriptor instead.
func (*UserEnabled) Descriptor() ([]byte, []int) {
	return file_userspb_messages_proto_rawDescGZIP(), []int{2}
}

func (x *UserEnabled) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserDisabled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserDisabled) Reset() {
	*x = UserDisabled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userspb_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDisabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDisabled) ProtoMessage() {}

func (x *UserDisabled) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDisabled.ProtoReflect.Descriptor instead.
func (*UserDisabled) Descriptor() ([]byte, []int) {
	return file_userspb_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UserDisabled) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuthorizeUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AuthorizeUser) Reset() {
	*x = AuthorizeUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userspb_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeUser) ProtoMessage() {}

func (x *AuthorizeUser) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeUser.ProtoReflect.Descriptor instead.
func (*AuthorizeUser) Descriptor() ([]byte, []int) {
	return file_userspb_messages_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizeUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_userspb_messages_proto protoreflect.FileDescriptor

var file_userspb_messages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x75, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73, 0x65, 0x72, 0x73, 0x70,
	0x62, 0x22, 0x4a, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x38, 0x0a,
	0x10, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x1d, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x85, 0x01, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x42, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2b, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x61,
	0x7a, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x70, 0x62, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x55, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x70, 0x62, 0xca, 0x02, 0x07, 0x55, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0xe2,
	0x02, 0x13, 0x55, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x55, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userspb_messages_proto_rawDescOnce sync.Once
	file_userspb_messages_proto_rawDescData = file_userspb_messages_proto_rawDesc
)

func file_userspb_messages_proto_rawDescGZIP() []byte {
	file_userspb_messages_proto_rawDescOnce.Do(func() {
		file_userspb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_userspb_messages_proto_rawDescData)
	})
	return file_userspb_messages_proto_rawDescData
}

var file_userspb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_userspb_messages_proto_goTypes = []interface{}{
	(*UserRegistered)(nil),   // 0: quizspb.UserRegistered
	(*UserEmailChanged)(nil), // 1: quizspb.UserEmailChanged
	(*UserEnabled)(nil),      // 2: quizspb.UserEnabled
	(*UserDisabled)(nil),     // 3: quizspb.UserDisabled
	(*AuthorizeUser)(nil),    // 4: quizspb.AuthorizeUser
}
var file_userspb_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userspb_messages_proto_init() }
func file_userspb_messages_proto_init() {
	if File_userspb_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userspb_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRegistered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userspb_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEmailChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userspb_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEnabled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userspb_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDisabled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userspb_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userspb_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userspb_messages_proto_goTypes,
		DependencyIndexes: file_userspb_messages_proto_depIdxs,
		MessageInfos:      file_userspb_messages_proto_msgTypes,
	}.Build()
	File_userspb_messages_proto = out.File
	file_userspb_messages_proto_rawDesc = nil
	file_userspb_messages_proto_goTypes = nil
	file_userspb_messages_proto_depIdxs = nil
}
